# Generated by Django 2.2.6 on 2019-10-22 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('anak_ke', models.IntegerField()),
                ('dari', models.IntegerField(blank=True, null=True)),
                ('agama', models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=10)),
                ('no_induk', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message="format berupa: '999999/ 999 999 / 999-999', min:5 digit, maks: 50 digit", regex='^\\d[0-9 -]{4,50}$')])),
                ('no_nik', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message="format berupa: '999999/ 999 999 / 999-999', min:5 digit, maks: 50 digit", regex='^\\d[0-9 -]{4,50}$')])),
                ('no_kk', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message="format berupa: '999999/ 999 999 / 999-999', min:5 digit, maks: 50 digit", regex='^\\d[0-9 -]{4,50}$')])),
                ('no_telp', models.CharField(blank=True, max_length=23, null=True, validators=[django.core.validators.RegexValidator(message="format berupa: '+999999 / +999 999 / +999-999, min:5 digit, maksimal 20 digit", regex='^\\+?\\d[0-9 -]{4,20}$')])),
                ('pendidikan_terakhir', models.CharField(choices=[('TK', 'Taman Kanak-kanak'), ('SD', 'Sekolah Dasar'), ('SMP/MTs', 'Sekolah Menengah Pertama'), ('SMA/MA', 'Sekolah Menengah Atas')], max_length=10)),
                ('alamat', models.TextField(max_length=300)),
                ('provinsi', models.CharField(max_length=50)),
                ('kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='santri_pics')),
                ('tanggal_masuk', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnggotaKeluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=20)),
                ('status', models.CharField(choices=[('Ayah', 'Ayah'), ('Ibu', 'Ibu'), ('Kakak', 'Kakak'), ('Adik', 'Adik')], max_length=10)),
                ('no_nik', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message="format berupa: '999999/ 999 999 / 999-999', min:5 digit,maks: 50 digit", regex='^\\d[0-9 -]{4,50}$')])),
                ('no_kk', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message="format berupa: '999999/ 999 999 / 999-999', min:5 digit,maks: 50 digit", regex='^\\d[0-9 -]{4,50}$')])),
                ('agama', models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=10)),
                ('no_telp', models.CharField(blank=True, max_length=23, null=True, validators=[django.core.validators.RegexValidator(message="format berupa: '+999999 / +999 999 / +999-999, min:5 digit, maks:20 digit", regex='^\\+?\\d[0-9 -]{4,20}$')])),
                ('alamat', models.TextField(max_length=300)),
                ('provinsi', models.CharField(max_length=50)),
                ('kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='kk_pics')),
                ('santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santri.Santri')),
            ],
        ),
    ]
