# Generated by Django 2.2.6 on 2019-10-23 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keperluan', models.CharField(choices=[('Periksa di Rumah Sakit', 'Periksa di Rumah Sakit'), ('Periksa di Puskesmas', 'Periksa di Puskesmas'), ('Hajatan - Nikah', 'Hajatan - Nikah'), ('Hajatan - Meninggal', 'Hajatan - Meninggal'), ('Lain-Lain', 'Lain-Lain')], max_length=30)),
                ('keterangan', models.TextField(blank=True, max_length=999, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Started', 'Masih berjalan'), ('Ended', 'Selesai')], max_length=20)),
                ('masa_durasi', models.DurationField(blank=True, choices=[(datetime.timedelta(1), '1 hari'), (datetime.timedelta(2), '2 hari'), (datetime.timedelta(3), '3 hari'), (datetime.timedelta(5), '5 hari'), (datetime.timedelta(7), '7 hari(1 minggu)'), (datetime.timedelta(14), '14 hari(2 minggu)'), (datetime.timedelta(30), '30 hari(1 bulan)')], null=True)),
                ('durasi_habis', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('anggotakeluarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santri.AnggotaKeluarga')),
                ('santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santri.Santri')),
            ],
        ),
        migrations.CreateModel(
            name='Keluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keperluan', models.CharField(choices=[('Periksa di Rumah Sakit', 'Periksa di Rumah Sakit'), ('Periksa di Puskesmas', 'Periksa di Puskesmas'), ('Belanja di Pasar', 'Belanja di Pasar'), ('Lain-Lain', 'Lain-Lain')], max_length=30)),
                ('keterangan', models.TextField(blank=True, max_length=999, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Started', 'Masih berjalan'), ('Ended', 'Selesai')], max_length=20)),
                ('masa_durasi', models.DurationField(blank=True, choices=[(datetime.timedelta(0, 900), '15 menit'), (datetime.timedelta(0, 1800), '30 menit'), (datetime.timedelta(0, 3600), '1 jam'), (datetime.timedelta(0, 7200), '2 jam'), (datetime.timedelta(0, 10800), '3 jam'), (datetime.timedelta(0, 18000), '5 jam'), (datetime.timedelta(0, 36000), '10 jam')], null=True)),
                ('durasi_habis', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santri.Santri')),
            ],
        ),
    ]
