# Generated by Django 2.2.6 on 2019-10-25 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0002_keluar_pulang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sambang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_penjenguk', models.CharField(blank=True, max_length=15, null=True)),
                ('menginap', models.BooleanField(default=False)),
                ('keterangan', models.TextField(blank=True, max_length=999, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Started', 'Masih berjalan'), ('Ended', 'Selesai')], max_length=20)),
                ('masa_durasi', models.DurationField(blank=True, choices=[(datetime.timedelta(0, 3600), '1 jam'), (datetime.timedelta(0, 7200), '2 jam'), (datetime.timedelta(0, 10800), '3 jam'), (datetime.timedelta(0, 18000), '5 jam'), (datetime.timedelta(0, 36000), '10 jam'), (datetime.timedelta(1), '1 hari'), (datetime.timedelta(2), '2 hari'), (datetime.timedelta(3), '3 hari'), (datetime.timedelta(5), '5 hari'), (datetime.timedelta(7), '7 hari(1 minggu)')], null=True)),
                ('durasi_habis', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('penjenguk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santri.AnggotaKeluarga')),
                ('santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santri.Santri')),
            ],
        ),
    ]
