# Generated by Django 2.2.6 on 2019-10-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0004_auto_20191026_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='keluar',
            name='no_invoice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pulang',
            name='no_invoice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sambang',
            name='no_invoice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='keluar',
            name='status',
            field=models.CharField(choices=[('Started', 'Masih keluar'), ('Ended', 'Selesai')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pulang',
            name='status',
            field=models.CharField(choices=[('Started', 'Masih pulang'), ('Ended', 'Selesai')], max_length=20),
        ),
    ]
