# Generated by Django 2.2.6 on 2019-10-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0005_auto_20191026_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keluar',
            name='sisa_waktu',
        ),
        migrations.RemoveField(
            model_name='pulang',
            name='sisa_waktu',
        ),
        migrations.RemoveField(
            model_name='sambang',
            name='sisa_waktu',
        ),
    ]
